# generated by datamodel-codegen:
#   filename:  nsr-openapi.json
#   timestamp: 2024-05-08T11:12:39+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Extra, constr, Field


class AdresseApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    address: Optional[str] = Field(validation_alias="Adresse", default=None)
    post_code: Optional[str] = Field(validation_alias="Postnr", default=None)
    city: Optional[str] = Field(validation_alias="Poststed", default=None)
    country: Optional[str] = Field(validation_alias="Land", default=None)


class BeliggenhetsadresseExternal(BaseModel):
    class Config:
        extra = Extra.forbid

    Adresse: Optional[constr(min_length=0, max_length=400)] = None
    Postnr: Optional[constr(min_length=4, max_length=4)] = None


class EnhetNaeringskodeApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    priority: Optional[int] = Field(validation_alias="Prioritet", default=None)
    is_help_unit_code: Optional[bool] = Field(validation_alias="ErHjelpeenhetskode", default=None)
    code: Optional[str] = Field(validation_alias="Kode", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)
    version: Optional[str] = Field(validation_alias="Versjon", default=None)


class EnhetUpdateResult(BaseModel):
    class Config:
        extra = Extra.forbid

    Orgnr: Optional[str] = None
    Ok: Optional[bool] = None
    Melding: Optional[str] = None


class FylkeApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    county_num: Optional[str] = Field(validation_alias="Fylkesnr", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)
    org_num: Optional[str] = Field(validation_alias="Orgnr", default=None)
    org_num_state_admin: Optional[str] = Field(validation_alias="OrgnrStatsforvalter", default=None)


class Hjelpeenhetskode(BaseModel):
    class Config:
        extra = Extra.forbid

    Kode: Optional[str] = None
    Beskrivelse: Optional[str] = None


class KommunegruppeApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    Gruppe: Optional[int] = None
    Navn: Optional[str] = None


class KoordinatApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    latitude: Optional[float] = Field(validation_alias="Breddegrad", default=0)
    longitude: Optional[float] = Field(validation_alias="Lengdegrad", default=0)
    zoom: Optional[int] = Field(validation_alias="Zoom", default=None)
    geo_source: Optional[str] = Field(validation_alias="GeoKilde", default=None)


class MaalformApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = Field(validation_alias="Id", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)


class NaeringskodeApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    Kode: Optional[str] = None
    Navn: Optional[str] = None
    Versjon: Optional[str] = None


class NsrEnhetTinyApiModelApiPageResult(BaseModel):
    class Config:
        extra = Extra.forbid

    page_num: Optional[int] = Field(validation_alias="Sidenummer", default=None)
    num_per_page: Optional[int] = Field(validation_alias="AntallPerSide", default=None)
    num_pages: Optional[int] = Field(validation_alias="AntallSider", default=None)
    total_units: Optional[int] = Field(validation_alias="TotaltAntallEnheter", default=None)
    units: Optional[List[NsrEnhetTinyApiModel]] = Field(validation_alias="Enheter", default=None)


class OrganisasjonsformApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    Id: Optional[str] = None
    Navn: Optional[str] = None


class PersonApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    Fornavn: Optional[str] = None
    Etternavn: Optional[str] = None
    Epost: Optional[str] = None
    Telefon: Optional[str] = None


class PostadresseExternal(BaseModel):
    class Config:
        extra = Extra.forbid

    Adresse: Optional[constr(min_length=0, max_length=400)] = None
    Postnr: Optional[str] = None


class PrivatskoleGodkjenningApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    Godkjenningslov: Optional[str] = None
    GodkjentStatus: Optional[str] = None
    GodkjentStatusTekst: Optional[str] = None
    ErAktiv: Optional[bool] = None


class RelasjonstypeApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = Field(validation_alias="Id", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)


class SkolekategoriApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    id: Optional[str] = Field(validation_alias="Id", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)


class SoekNsrApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    FritekstSoek: Optional[str] = None
    Naeringskode: Optional[str] = None
    SkolekategoriId: Optional[str] = None
    Fylkenr: Optional[str] = None
    Kommunenr: Optional[str] = None
    InkluderNedlagte: Optional[bool] = None
    InkluderAktive: Optional[bool] = None
    InkluderSkoler: Optional[bool] = None
    InkluderEiere: Optional[bool] = None
    InkluderAndreEnheter: Optional[bool] = None


class UtgaattypeApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    Id: Optional[str] = None
    Navn: Optional[str] = None


class EnhetExternal(BaseModel):
    class Config:
        extra = Extra.forbid

    Orgnr: constr(min_length=9, max_length=9)
    Navn: constr(min_length=0, max_length=400)
    Epost: Optional[constr(min_length=0, max_length=400)] = None
    Telefon: Optional[constr(min_length=0, max_length=400)] = None
    Mobil: Optional[constr(min_length=0, max_length=400)] = None
    Beliggenhetsadresse: BeliggenhetsadresseExternal
    Postadresse: Optional[PostadresseExternal] = None


class KommuneApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    municipality_num: Optional[str] = Field(validation_alias="Kommunenr", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)
    org_num: Optional[str] = Field(validation_alias="Orgnr", default=None)
    is_decommissioned: Optional[bool] = Field(validation_alias="ErNedlagt", default=None)
    county_num: Optional[str] = Field(validation_alias="Fylkesnr", default=None)
    municipality_group: Optional[KommunegruppeApiModel] = Field(validation_alias="Kommunegruppe", default=None)


class NsrRelasjonApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    unit: Optional[EnhetMinimumApiModel] = Field(validation_alias="Enhet", default=None)
    relation_type: Optional[RelasjonstypeApiModel] = Field(validation_alias="Relasjonstype", default=None)


class UpdateEnheterPayload(BaseModel):
    class Config:
        extra = Extra.forbid

    BrukernavnEksternt: constr(min_length=1)
    Enheter: Optional[List[EnhetExternal]] = None


class EnhetMinimumApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    org_num: Optional[str] = Field(validation_alias="Orgnr", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)


class NsrEnhetTinyApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    org_num: Optional[str] = Field(validation_alias="Orgnr", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)
    characteristic: Optional[str] = Field(validation_alias="Karakteristikk", default=None)
    county_num: Optional[str] = Field(validation_alias="Fylkesnr", default=None)
    municipality_num: Optional[str] = Field(validation_alias="Kommunenr", default=None)
    email: Optional[str] = Field(validation_alias="Epost", default=None)
    is_active: Optional[bool] = Field(validation_alias="ErAktiv", default=None)
    is_school: Optional[bool] = Field(validation_alias="ErSkole", default=None)
    is_school_owner: Optional[bool] = Field(validation_alias="ErSkoleeier", default=None)
    is_primary_education: Optional[bool] = Field(validation_alias="ErGrunnskole", default=None)
    is_secondary_education: Optional[bool] = Field(validation_alias="ErVideregaaendeSkole", default=None)
    is_private_school: Optional[bool] = Field(validation_alias="ErPrivatskole", default=None)
    is_public_school: Optional[bool] = Field(validation_alias="ErOffentligSkole", default=None)
    is_special_school: Optional[bool] = Field(validation_alias="ErSpesialskole", default=None)
    is_basic_training: Optional[bool] = Field(validation_alias="ErGrunnopplaering", default=None)
    date_changed: Optional[datetime] = Field(validation_alias="DatoEndret", default=None)

    @property
    def is_relevant(self):
        return self.is_active and self.is_school and (self.is_primary_education or self.is_secondary_education)


class NsrEnhetApiModel(BaseModel):
    class Config:
        extra = Extra.forbid

    org_num: Optional[str] = Field(validation_alias="Orgnr", default=None)
    name: Optional[str] = Field(validation_alias="Navn", default=None)
    characteristic: Optional[str] = Field(validation_alias="Karakteristikk", default=None)
    county: Optional[FylkeApiModel] = Field(validation_alias="Fylke", default=None)
    municipality: Optional[KommuneApiModel] = Field(validation_alias="Kommune", default=None)
    location_address: Optional[AdresseApiModel] = Field(validation_alias="Beliggenhetsadresse", default=None)
    post_address: Optional[AdresseApiModel] = Field(validation_alias="Postadresse", default=None)
    coordinate: Optional[KoordinatApiModel] = Field(validation_alias="Koordinat", default=None)
    email: Optional[str] = Field(validation_alias="Epost", default=None)
    url: Optional[str] = Field(validation_alias="Url", default=None)
    written_language: Optional[MaalformApiModel] = Field(validation_alias="Maalform", default=None)
    telephone: Optional[str] = Field(validation_alias="Telefon", default=None)
    mobile_phone: Optional[str] = Field(validation_alias="Mobil", default=None)
    fax: Optional[str] = Field(validation_alias="Fax", default=None)
    organisation_form: Optional[OrganisasjonsformApiModel] = Field(validation_alias="Organisasjonsform", default=None)
    business_codes: Optional[List[EnhetNaeringskodeApiModel]] = Field(validation_alias="Naeringskoder", default=None)
    help_unit_code: Optional[Hjelpeenhetskode] = Field(validation_alias="Hjelpeenhetskode", default=None)
    expired_type: Optional[UtgaattypeApiModel] = Field(validation_alias="Utgaattype", default=None)
    is_active: Optional[bool] = Field(validation_alias="ErAktiv", default=None)
    is_school: Optional[bool] = Field(validation_alias="ErSkole", default=None)
    is_school_owner: Optional[bool] = Field(validation_alias="ErSkoleeier", default=None)
    is_primary_education: Optional[bool] = Field(validation_alias="ErGrunnskole", default=None)
    is_private_school: Optional[bool] = Field(validation_alias="ErPrivatskole", default=None)
    is_public_school: Optional[bool] = Field(validation_alias="ErOffentligSkole", default=None)
    is_secondary_education: Optional[bool] = Field(validation_alias="ErVideregaaendeSkole", default=None)
    is_special_school: Optional[bool] = Field(validation_alias="ErSpesialskole", default=None)
    is_basic_training: Optional[bool] = Field(validation_alias="ErGrunnopplaering", default=None)
    private_school_approval: Optional[PrivatskoleGodkjenningApiModel] = Field(validation_alias="PrivatskoleGodkjenning", default=None)
    school_leader: Optional[PersonApiModel] = Field(validation_alias="Skoleleder", default=None)
    num_pupils: Optional[int] = Field(validation_alias="Elevtall", default=None)
    employees_from: Optional[int] = Field(validation_alias="AnsatteFra", default=None)
    employees_to: Optional[int] = Field(validation_alias="AnsatteTil", default=None)
    grade_gs_from: Optional[int] = Field(validation_alias="SkoletrinnGSFra", default=None)
    grade_gs_to: Optional[int] = Field(validation_alias="SkoletrinnGSTil", default=None)
    grade_vgs_from: Optional[int] = Field(validation_alias="SkoletrinnVGSFra", default=None)
    grade_vgs_to: Optional[int] = Field(validation_alias="SkoletrinnVGSTil", default=None)
    school_categories: Optional[List[SkolekategoriApiModel]] = Field(validation_alias="Skolekategorier", default=None)
    parent_relations: Optional[List[NsrRelasjonApiModel]] = Field(validation_alias="ForeldreRelasjoner", default=None)
    child_relations: Optional[List[NsrRelasjonApiModel]] = Field(validation_alias="BarnRelasjoner", default=None)
    date_created: Optional[datetime] = Field(validation_alias="DatoFoedt", default=None)
    date_changed: Optional[datetime] = Field(validation_alias="DatoEndret", default=None)
